version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command:
      [
        "postgres",
        "-c", "wal_level=logical",
        "-c", "max_wal_senders=10",
        "-c", "max_replication_slots=10"
      ]
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  debezium:
    image: debezium/server:2.5
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # --- Google Cloud credentials ---
      - GOOGLE_APPLICATION_CREDENTIALS=/debezium/conf/key.json
      - GOOGLE_CLOUD_PROJECT=<YOUR-GCP-PROJECT-ID>   # <-- change to your real project ID
    volumes:
      - ./conf:/debezium/conf
      - ./data:/debezium/data
      - ./conf:/debezium/conf
    ports:
      - "8080:8080"   # optional: Debezium Server metrics endpoint

volumes:
  pgdata:
